In [8]:
import numpy as np
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
from sklearn.neighbors import KNeighborsClassifier


In [95]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12],
              [13, 14, 15]])


## Two loop

In [96]:
num_test = A.shape[0]
num_train = B.shape[0]
dists = np.zeros((num_test, num_train))
for i in range(num_test):
    for j in range(num_train):
        R = A[i] - B[j]
        dists[i][j] =  np.sqrt(np.sum(R.T@R))
dists

array([[10.39230485, 15.58845727, 20.78460969],
       [ 5.19615242, 10.39230485, 15.58845727]])

## No loop

$(A -B)^T(A -B) = A^TA - 2*A^TB + B^TB$

In [97]:
np.sqrt((np.diag(A@A.T) - 2*(A@B.T).T).T + np.diag(B@B.T))

array([[10.39230485, 15.58845727, 20.78460969],
       [ 5.19615242, 10.39230485, 15.58845727]])

## One loop

In [99]:
dists = np.zeros((num_test, num_train))
for i in range(num_test):
    R = A[i] - B
    dists[i] = np.sqrt(np.diag(R@R.T))
dists

array([[10.39230485, 15.58845727, 20.78460969],
       [ 5.19615242, 10.39230485, 15.58845727]])

# Tests

In [108]:
A = np.array([[1,7,3,4,5,6,1,2,6],[3,2,5,6,1,2,6,10,11]])
b = [1,0,0,2,3,3,4,2,1]
lables = list(set(b))

In [109]:
a = A[0]
k = 2
np.argsort(a)[:k]

array([0, 6])